### ISSUE TITLE
option to use --f5 ssl for decryption keys

### ISSUE THREAD

**Issue by Larsende** [f5-rahm/pcap_utils#2]
I think it would be more efficient and performant to use the --f5 ssl option to put the TLS shared secret keys into the packet capture and then use tshark command to pull the keys out to file.  Support has started to use this method for hosts >15.1 instead of the iRule method.  If sticking with the iRule method and you want to decrypt TLS1.3 you will need to add more to the iRule.  Check here: https://clouddocs.f5.com/training/community/adc/html/class4/module1/lab12.html#decrypt-ssl-with-irule.

**Comment by f5-rahm** [comment]
Hi @Larsende, I had considered this for sure, but I got some feedback from a couple people that there might be some corner cases where --f5 might not work. Nothing confirmed, however, so I'll revisit.

**Comment by f5-rahm** [comment]
Hi @Larsende, this has been merged: https://github.com/f5-rahm/pcap_utils/pull/4. New script: https://github.com/f5-rahm/pcap_utils/blob/main/TLSv1_3_captures.py. Also does the decryption automatically.
